# Production override for docker-compose.yml
# Use with: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  backend:
    environment:
      DEBUG: "false"
      # Production optimizations
      ENABLE_INTERNET_SEARCH: "false"
      RAG_USE_CPU: "true"
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8010", "--workers", "1"]
    volumes:
      # Remove source code mount in production
      - ./models:/app/models:ro
      - ./logs:/app/logs
    restart: unless-stopped
    # Conservative resource limits for production
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: 2.0
        reservations:
          memory: 2G
          cpus: 1.0

  frontend:
    # Enable frontend service in production
    profiles: []

  postgres:
    # Add resource limits for database
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: 1.0
        reservations:
          memory: 512M
          cpus: 0.5

  weaviate:
    # Add resource limits for vector database
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: 1.0
        reservations:
          memory: 1G
          cpus: 0.5 